name: Build

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
      - '.github/dependabot.yml'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          target: build-stage
